[package]
name = "pqc_core"
version = "0.1.0"
edition = "2021"
authors = ["Mitchell Berry <foss@mitchellberry.com>"]
readme = "readme.md"
repository = "https://github.com/Argyle-Software/pqc_core"
license = "MIT OR Apache-2.0"

[dependencies]

[features]
load = []
